### ISSUE TITLE
Use nf instead of whnf for lazy text

### ISSUE THREAD

**Issue by noughtmare** [AndreasPK/nubBench#1]
Using nf will force the lazy nub functions to actually do some work, right now, as is visible from the benchmark results, the lazy nub functions do nothing.

**Comment by AndreasPK** [comment]
The idea behind the lazy benchmarks is exactly to show how strict/lazy these functions are and that the lazy ones won't do work unless demanded.

Forcing the whole result using nf would defeat the purpose. The strict benchmark already measures performance if we demand the result, since length forces the spine.

**Comment by noughtmare** [comment]
Ah, I got the wrong idea then.
